### ISSUE TITLE
Add soft wrap feature

### ISSUE THREAD

**Issue by stdex** [fortharris/Pcode#12]
Hello.
Eage line works fine when people write new code.
If we have existing code we need soft wrap feature.
Can you add this option?

**Comment by fortharris** [comment]
Can you please explain what Eage line is?

**Comment by stdex** [comment]
* edge mode: line

**Comment by fortharris** [comment]
OK. By soft wrap, you you intend to insert line breaks manually. I'm i correct?

**Comment by stdex** [comment]
Feature like that: http://www.youtube.com/watch?v=_gxr5EFrnOI

**Comment by fortharris** [comment]
I get what you mean now. I will look into Qsciscintilla to see if there is a control for that since that will be the most efficient way to implement it.

**Comment by stdex** [comment]
Looks like function: QsciScintilla::setWrapMode

**Comment by fortharris** [comment]
Thanks. Will definitely add that feature.

**Comment by stdex** [comment]
Also, scroll not working correct with long lines:
![image](https://cloud.githubusercontent.com/assets/4608879/8634166/c07fed54-27f6-11e5-8df9-4f8653b8d128.png)

**Comment by fortharris** [comment]
This could be a problem with Qsciscintilla. You can however shorten long lines by escaping them at the commas. I believe this also makes for a neater code.
