### ISSUE TITLE
Feature request: recheck syntax after all changes

### ISSUE THREAD

**Issue by stdex** [fortharris/Pcode#13]
I have problem... Sometimes I have situation when syntax are valid, but I can see message "Invalid syntax".
![image](https://cloud.githubusercontent.com/assets/4608879/8567862/50f0f8e8-2571-11e5-8431-c16632c62eea.png)

**Comment by fortharris** [comment]
Thanks. Currently the editor uses a timer with a zero interval which means that it sets off as soon as editing completes and then the syntax is checked. I suppose that i just have to increase the interval by a few seconds just so the editor waits a bit longer before checking syntax.

**Comment by fortharris** [comment]
Problem solved itself after I updated the library.
