### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by tastyminerals** [fortharris/Pcode#15]
Trying out Pcode on linux41 x64 machine.
I clone Pcode from git and run it with `python3 Pcode.py`.
I then register a workspace and attempt to create my first project.
I am using "Desktop application" and "console" options and constantly receive the following error:
`Problem opening project: 
dictionary changed size during iteration`
This happens both with current git clone and with the zip snapshot provided.

**Comment by fortharris** [comment]
Sorry for the late reply. Pcode has a LOG.txt file saved up in the workspace folder. Kindly look through and show me the content regarding this error.
